version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafkanet
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES=30000000 # 3MB per client response
      - KAFKA_CFG_MAX_REQUEST_SIZE=30000000 # 3MB per client request
    volumes:
      - ./kafka/volume:/bitnami/kafka
      # - ./volume/server.properties:/bitnami/kafka/config/server.properties
      # - ./producer.properties:/bitnami/kafka/config/producer.properties
    depends_on:
      - zookeeper
    networks:
      - kafkanet
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --describe"]
      start_period: 15s
      interval: 20s
      timeout: 20s
      retries: 5
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    networks:
      - kafkanet
networks:
  kafkanet:
    driver: bridge