build:
	@sudo docker build -t nalbertgml/motor_plates_detector:latest -f dockerfile ../..
run:
	@sudo docker run -d --name motor-plates-detector nalbertgml/motor_plates_detector:latest
stop:
	@sudo docker stop motor-plates-detector