build:
	@sudo docker build -t nalbertgml/motor_detector:latest -f dockerfile ../..
run:
	@sudo docker run -d --name motor-detector nalbertgml/motor_detector:latest
stop:
	@sudo docker stop motor-detector