FROM python:3.10.4-slim
# FROM nalbertgml/cuda-10.2-cudnn8-devel-ubuntu18.04-opencv-4.5.4:latest
# FROM nalbertgml/opencv:4.6.0-cc8.6-cuda11.7.0-cudnn8-runtime-ubuntu20.04
WORKDIR app/

COPY projects/plate_characters_detector/ .
COPY libs/image_processing_lib ../libs/image_processing_lib/
COPY libs/kafka_lib/ ../libs/kafka_lib/
COPY libs/mongodb_lib/ ../libs/mongodb_lib/
COPY utils/protobuf/py/ .

# setup non interactive terminal
ARG DEBIAN_FRONTEND=noninteractive
# setup language
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
#Turns off buffering
ENV PYTHONUNBUFFERED 1
# install python
# RUN apt update && \
#     apt install --no-install-recommends -y python3.8 python3-pip python3.8-dev
# install opencv
RUN apt-get update && apt-get install -y python3-opencv
# clean apt cache
RUN apt install -y
RUN rm -rf /var/lib/apt/lists/* 
RUN apt purge   --auto-remove 
RUN apt clean

RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install numpy --upgrade

ENV KAFKA_HOST kafka:29092
ENV MONGO_HOST mongodb
ENV MONGO_PORT 27017
ENV MONGO_USER root
ENV MONGO_PASS 231564
# dont use gpu, it's broken
#ENV USE_GPU 0

CMD python3 main.py